### ISSUE TITLE
mixed space and tab in OpenNI/Platform/Win32/CreateRedist/*.py

### ISSUE THREAD

**Issue by tnadmin** [OpenNI/OpenNI#37] opened 2011-09-24 12:22 UTC
there are mixed use of spaces and tabs in OpenNI/Platform/Win32/CreateRedist/*.py, rendering them not usable at all without fixing manually.
i didn't check the other scripts, but they are likely suffering the same problem too.

**Comment by OpenNI** [comment] 2011-11-14 18:08
Can you please paste the exact error?
What's the python version you are using?
I cannot reproduce it...

**Comment by tnadmin** [comment] 2011-11-15 00:48
search for space and/or tabs, you will find them in the indentation.

**Comment by OpenNI** [comment] 2011-12-22 20:13
All fixed in the latest version.
Thanks!
Ziv.

**Closed as completed by OpenNI** 2011-12-22 20:13 UTC
